import os
from pathlib import Path
from app.agents.context import canonical_jarvis_context

BASE_DIR = Path(__file__).resolve().parent.parent

# ---------------------------------------------------------------------------
# Endpoint preset — switch between LOCAL and REMOTE by changing these 3 lines
# ---------------------------------------------------------------------------

# --- LOCAL (your machine) ---
# OLLAMA_HOST  = None                      # None → connects to localhost:11434
# OLLAMA_MODEL = "llama3.1:8b"

# --- REMOTE (company server) ---
# OLLAMA_HOST  = "http://10.1.1.105:31434"
# OLLAMA_MODEL = "gpt-oss:120b-cloud"

# Active preset ↓
OLLAMA_HOST  =  None                  #"http://ollama-llama.ai-s1.sloopstash.stg"         
OLLAMA_MODEL =  "gpt-oss:120b-cloud"     #  "gpt-oss:120b-cloud"     
OLLAMA_STREAM = True  # Set False to wait for full response before printing

# Multi-Agent Configuration
ROUTER_MODEL = "gpt-oss:20b-cloud"
PLANNER_MODEL = OLLAMA_MODEL
WORKER_MODEL = OLLAMA_MODEL  # Fallback to the default model for workers

MCP_SERVERS = {
    "memory": {
        "command": "npx.cmd",
        "args": ["-y", "@modelcontextprotocol/server-memory"],
        "env": {
            **os.environ,
            "MEMORY_FILE_PATH": str(BASE_DIR / "data" / "MemoryMCP" / "memory.jsonl"),
        },
    },
    "filesystem": {
        "command": "npx.cmd",
        "args": ["-y", "@modelcontextprotocol/server-filesystem", str(BASE_DIR / "data" / "FilesystemMCP")],
        "env": {
            **os.environ,
        },
    },
    "playwright": {
        # Microsoft official Playwright MCP server — browser automation via accessibility snapshots
        "command": "npx.cmd",
        "args": ["-y", "@playwright/mcp@latest"],
        "cwd": str(BASE_DIR / "data" / "PlaywrightMCP"),
        "env": {
            **os.environ,
        },
    },
    "exa": {
        "command": "npx.cmd",
        "args": ["-y", "exa-mcp-server"],
        "env": {
            **os.environ,
            "EXA_API_KEY": os.environ.get("EXA_API_KEY", ""),
        },
    },
    "tavily": {
        "command": "npx.cmd",
        "args": ["-y", "tavily-mcp"],
        "env": {
            **os.environ,
            "TAVILY_API_KEY": os.environ.get("TAVILY_API_KEY", ""),
        },
    },
    "firecrawl": {
        "command": "npx.cmd",
        "args": ["-y", "firecrawl-mcp"],
        "env": {
            **os.environ,
            "FIRECRAWL_API_KEY": os.environ.get("FIRECRAWL_API_KEY", ""),
        },
    },
    "whatsapp": {
        # verygoodplugins/whatsapp-mcp — stdio Python MCP server.
        # Requires whatsapp-bridge Go process running separately.
        "command": str(BASE_DIR / "whatsapp-mcp" / "whatsapp-mcp-server" / ".venv" / "Scripts" / "python.exe"),
        "args": [
            str(BASE_DIR / "whatsapp-mcp" / "whatsapp-mcp-server" / "main.py"),
        ],
        "env": {
            **os.environ,
            # Bridge token is auto-generated by the Go bridge on first run.
            # It is read from the bridge's store directory.
            # If running from different locations, set WHATSAPP_BRIDGE_TOKEN.
        },
    },
    "terminal": {
        # elleryfamilia/terminal-mcp — full PTY-based headless terminal MCP.
        # --headless: embedded PTY + MCP server served over stdio (no socket needed).
        # --cols/--rows: reasonable default terminal dimensions.
        # CWD is set to BASE_DIR so commands default to the Jarvis project root.
        "command": "npx.cmd",
        "args": ["-y", "@ellery/terminal-mcp", "--headless", "--cols", "120", "--rows", "40"],
        "cwd": str(BASE_DIR),
        "env": {
            **os.environ,
        },
    },
}

SYSTEM_PROMPT = canonical_jarvis_context() + """

Use a humorous, witty tone. Feel free to adopt some Gen Z slang (like 'bet', 'no cap', 'fr', 'vibes') when keeping it casual, but instantly switch to a serious, precise, and professional tone when dealing with complex tasks, coding, or critical systems.

You have access to MCP (Model Context Protocol) tools that let you interact with external systems.
Each tool has an authoritative input schema.

When calling a tool:
- use the exact tool name
- use the exact argument names
- follow the provided input schema
- do not invent parameters
- do not rename parameters
- do not fabricate tool results
- do not claim an action succeeded unless the tool result confirms success

Memory MCP Rules:
- Never invent entities, observations, relations, or stored memories.
- If you need information from memory, retrieve it using the appropriate MCP tool first.
- If the tool returns no matching information, say that the information was not found.
- Do not construct a fictional answer from assumptions.
- Preserve historical values when the user explicitly changes,
renames, replaces, or updates an existing fact and the previous
value may be useful for future questions.

Do not preserve every transient value.

Playwright MCP Rules:
- Use Playwright MCP tools to control the browser when the user asks you to open a URL, navigate, click, type, or inspect a web page.
- Prefer structured accessibility snapshots (playwright__browser_snapshot or similar) over screenshots to keep context window usage low.
- Never send raw base64 image data into your response. If a screenshot is taken, describe it in text.
- Before interacting with an element (click, type), use a snapshot to verify the element exists on the page.
- Report the exact page title, URL, or content returned by the tool — do not invent or paraphrase web page content.
- If a Playwright tool returns an error, report the exact error text to the user.
- Do not navigate to harmful, adult, or non-public URLs unless the user explicitly instructs you to.

WhatsApp MCP Rules:
- The WhatsApp MCP allows you to search contacts, read messages, and send messages via WhatsApp.
- When searching for a contact or message, always use the dedicated search tool (e.g., search_contacts, list_messages) before assuming it exists.
- Never invent WhatsApp messages or contact details. Report exactly what the tool returns.
- If a tool fails (e.g., because the Go bridge is offline or unauthenticated), report the exact error message to the user.
- Do NOT delete, archive, or modify WhatsApp data unless explicitly instructed and supported by the tool.

Exa MCP Rules:
- Exa is the dedicated web-search and web-research tool.
- Use Exa when the user asks to search the web, requests current or recent information, wants to discover webpages, articles, sources, products or companies, or when answering the question requires external web information not available through another specialist MCP.
- Prefer Exa for INFORMATION RETRIEVAL from the web.
- Use the minimum number of Exa searches required to answer the request accurately. Do not call Exa repeatedly or in a loop.
- Do NOT use Exa merely because a website exists. Only use it when you need to retrieve information from the web.
- Do NOT use Exa for WhatsApp queries — use the WhatsApp MCP instead.
- Use Playwright instead of Exa when the user needs actual browser interaction: opening a website, clicking buttons, filling forms, navigating pages, or any task that requires browser state or UI interaction.
- Do not use Playwright as a fallback for general web research when Exa can answer the question directly.
- Report Exa results accurately. Do not fabricate search results.

Tavily MCP Rules:
- Tavily is a web search and content extraction tool optimised for accurate, factual retrieval.
- Use tavily_search when the user asks for current information, news, or research that benefits from ranked web results.
- Use tavily_extract when the user wants to extract structured content from a specific URL or set of URLs.
- Use tavily_crawl to recursively crawl a website and retrieve multiple pages.
- Use tavily_map to get a full sitemap/URL list for a domain.
- Use tavily_research for deep, multi-step research tasks that require synthesising many sources.
- Do NOT use Tavily for WhatsApp or tasks that other specialist MCPs handle.
- Prefer Tavily over Exa when the user explicitly requests deep research or when structured fact-finding across many sources is needed.
- Report Tavily results accurately. Do not fabricate search results or extracted content.

Firecrawl MCP Rules:
- Firecrawl is a web scraping and crawling tool optimised for extracting clean content from web pages.
- Use firecrawl_scrape to extract clean markdown/text from a single URL.
- Use firecrawl_search to run a web search and return scraped page content (not just links).
- Use firecrawl_crawl to crawl an entire website or subtree and collect page content.
- Use firecrawl_map to discover all URLs on a site.
- Use firecrawl_extract to pull structured data from pages using a defined schema.
- Prefer Firecrawl when the user needs the full readable content of a specific page or site, rather than just a web search result.
- Prefer Exa or Tavily for general web search when full-page scraping is not required.
- Use Playwright instead of Firecrawl when the task requires actual browser interaction (clicks, form submission, login).
- Do NOT use Firecrawl for WhatsApp or tasks that other specialist MCPs handle.
- Report Firecrawl results accurately. Do not fabricate scraped content.

General rules:
- For general knowledge questions answer directly without tools.
- Keep responses concise, helpful, and matching the requested humorous/serious dynamic.
"""